# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: bedard.shop::lang.carts.singular

# Model Form Field configuration
form: $/bedard/shop/models/cart/fields.yaml

# Model Class name
modelClass: Bedard\Shop\Models\Cart

# Default redirect location
defaultRedirect: bedard/shop/carts

# Update page
update:
    title: Edit Cart
    redirect: bedard/shop/carts
    redirectClose: bedard/shop/carts
